### ISSUE TITLE
Merge datasets

### ISSUE THREAD

**Issue by evgenyarol** [openvinotoolkit/datumaro#1143]
I attempted to merge two datasets from Roboflow for Yolov8. I set up two projects: project1 and project2. After copying the datasets into these directories, I tried to merge them using the command sudo datum merge -p project1 -o merged_project project2. However, I encountered an error indicating missing image files, even though the files do exist (I've checked). Could you advise on how to rectify this error or provide the proper workflow for merging? 

Thank you!

853 ERROR: Failed to import item ('1678819097003591_mp4-1591_jpg.rf.dbf1c85b160e1ae300475e37556a29e0', 'labels'): '1678819097003591_mp4-1591_jpg.rf.dbf1c85b160e1ae300475e37556a29e0'
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.10/site-packages/datumaro/plugins/data_formats/yolo/base.py", line 339, in __iter__
    img = Image.from_file(path=self._img_files[fname])
KeyError: '1678819097003591_mp4-1591_jpg.rf.dbf1c85b160e1ae300475e37556a29e0'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/ubuntu/.local/bin/datum", line 8, in <module>
    sys.exit(main())
  File "/home/ubuntu/.local/lib/python3.10/site-packages/datumaro/cli/__main__.py", line 150, in main
    retcode = args.command(args)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/datumaro/util/scope.py", line 158, in wrapped_func
    ret_val = func(*args, **kwargs)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/datumaro/cli/commands/merge.py", line 270, in merge_command
    merged_dataset = HLOps.merge(
  File "/home/ubuntu/.local/lib/python3.10/site-packages/datumaro/components/hl_ops/__init__.py", line 177, in merge
    merged = merger(*datasets)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/datumaro/components/merge/base.py", line 81, in __call__
    parent=self.merge(datasets), infos=infos, categories=categories, media_type=media_type
  File "/home/ubuntu/.local/lib/python3.10/site-packages/datumaro/components/merge/union_merge.py", line 41, in merge
    for item in source:
  File "/home/ubuntu/.local/lib/python3.10/site-packages/datumaro/components/dataset.py", line 284, in __iter__
    yield from self._data
  File "/home/ubuntu/.local/lib/python3.10/site-packages/datumaro/components/dataset_storage.py", line 351, in __iter__
    yield from self._iter_init_cache()
  File "/home/ubuntu/.local/lib/python3.10/site-packages/datumaro/components/dataset_storage.py", line 185, in _iter_init_cache
    for item in self._iter_init_cache_unchecked():
  File "/home/ubuntu/.local/lib/python3.10/site-packages/datumaro/components/dataset_storage.py", line 259, in _iter_init_cache_unchecked
    for i, item in enumerate(source):
  File "/home/ubuntu/.local/lib/python3.10/site-packages/datumaro/components/project.py", line 133, in __iter__
    yield from self._dataset
  File "/home/ubuntu/.local/lib/python3.10/site-packages/datumaro/components/dataset.py", line 284, in __iter__
    yield from self._data
  File "/home/ubuntu/.local/lib/python3.10/site-packages/datumaro/components/dataset_storage.py", line 351, in __iter__
    yield from self._iter_init_cache()
  File "/home/ubuntu/.local/lib/python3.10/site-packages/datumaro/components/dataset_storage.py", line 188, in _iter_init_cache
    raise e.__cause__
datumaro.components.errors.ItemImportError: Failed to import item ('1678819097003591_mp4-1591_jpg.rf.dbf1c85b160e1ae300475e37556a29e0', 'labels'): '1678819097003591_mp4-1591_jpg.rf.dbf1c85b160e1ae300475e37556a29e0'

**Comment by sooahleex** [comment]
Hi @evgenyarol Sorry for late response.

I checked the case you mentioned like below flow. I have created two small datasets in the `roboflow_yolo` format, each containing 30 annotated items.

```
cd ~/test
datum project create -o ./project1
datum project create -o ./project2

datum project import --format roboflow_yolo -p ./project1 ~/data/roboflow/yolov8_small_1
datum project import --format roboflow_yolo -p ./project2 ~/data/roboflow/yolov8_small_2

datum merge --merge-policy union --format imagenet --output-dir ./merged_output ./project1 ./project2 -- --save-media
```
It works out for me. I referred to the process of merging datasets [here](https://openvinotoolkit.github.io/datumaro/latest/docs/level-up/intermediate_skills/07_data_merge.html), you can check the `ProjectCLI`. 
In the case of 'roboflow_yolo,' since export is not supported, you can check this in this [roboflow_yolo doc](https://openvinotoolkit.github.io/datumaro/latest/docs/data-formats/formats/roboflow.html#roboflow-yolov5-yolov7-yolov8-txt), I configured an arbitrary format using `imagenet` for testing. If my experimental results differ from your intentions, could you please share the CLI code you tested with and a portion of the dataset?
Additionally, I would appreciate it if you could let me know which version of Datumaro you used.

**Comment by wonjuleee** [comment]
@evgenyarol, if there is any issue, please reopen the issue. Thank you for your interests!
