### ISSUE TITLE
Cant import or convert roboflow dataset

### ISSUE THREAD

**Issue by baudneo** [openvinotoolkit/datumaro#1160]
I must be doing something wrong but, I am following the Basic Skills example from datamuro user guide and getting errors at the very first step.

I exported my dataset from Roboflow using VOC. I unzipped the zip into its own dir @ `/root/voc`. It has `train/ test/ valid/` sub dirs.

I tried CLI and IDLE:

# Tree output
```
╰─❯ tree -d ~/voc
/root/voc
├── test
├── train
└── valid
```
# Import
## CLI

```
╰─❯ datum project import -n cm-v7 -f roboflow_voc -p ../datamuro/projects/roboflow ~/voc
2023-10-01 14:50:07,936 INFO: Checking the source...
2023-10-01 14:50:08,981 ERROR: Failed to find dataset 'roboflow_voc' at '/root/datamuro/projects/roboflow/cm-v7'
Traceback (most recent call last):
  File "/root/datamuro/projects/venv/bin/datum", line 8, in <module>
    sys.exit(main())
  File "/root/datamuro/projects/venv/lib/python3.9/site-packages/datumaro/cli/__main__.py", line 150, in main
    retcode = args.command(args)
  File "/root/datamuro/projects/venv/lib/python3.9/site-packages/datumaro/util/scope.py", line 158, in wrapped_func
    ret_val = func(*args, **kwargs)
  File "/root/datamuro/projects/venv/lib/python3.9/site-packages/datumaro/cli/commands/require_project/modification/import_.py", line 176, in import_command
    project.working_tree.make_dataset(name)
  File "/root/datamuro/projects/venv/lib/python3.9/site-packages/datumaro/components/project.py", line 1556, in make_dataset
    return ProjectBuilder(self._project, self).make_dataset(pipeline)
  File "/root/datamuro/projects/venv/lib/python3.9/site-packages/datumaro/components/project.py", line 379, in make_dataset
    dataset = self._get_resulting_dataset(pipeline)
  File "/root/datamuro/projects/venv/lib/python3.9/site-packages/datumaro/components/project.py", line 444, in _get_resulting_dataset
    graph, head = self._run_pipeline(pipeline)
  File "/root/datamuro/projects/venv/lib/python3.9/site-packages/datumaro/components/project.py", line 441, in _run_pipeline
    return self._init_pipeline(pipeline, working_dir_hashes=wd_hashes)
  File "/root/datamuro/projects/venv/lib/python3.9/site-packages/datumaro/components/project.py", line 573, in _init_pipeline
    dataset = _try_load_from_disk(stage_name, stage_config)
  File "/root/datamuro/projects/venv/lib/python3.9/site-packages/datumaro/components/project.py", line 552, in _try_load_from_disk
    return ProjectSourceDataset(
  File "/root/datamuro/projects/venv/lib/python3.9/site-packages/datumaro/components/project.py", line 99, in __init__
    dataset = Dataset.import_from(rpath, env=tree.env, format=config.format, **config.options)
  File "/root/datamuro/projects/venv/lib/python3.9/site-packages/datumaro/components/dataset.py", line 700, in import_from
    else importer(path, **kwargs)
  File "/root/datamuro/projects/venv/lib/python3.9/site-packages/datumaro/components/importer.py", line 67, in __call__
    raise DatasetNotFoundError(path, self.NAME)
datumaro.components.errors.DatasetNotFoundError: Failed to find dataset 'roboflow_voc' at '/root/datamuro/projects/roboflow/cm-v7'
```

## IDLE

```
╰─❯ python3
Python 3.9.2 (default, Feb 28 2021, 17:03:44)
[GCC 10.2.1 20210110] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from datumaro.components.dataset import Dataset
^[[Adata_path = '/root/voc'
>>> data_format="roboflow_voc"
>>> dataset = Dataset.import_from(data_path, data_format)

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/root/datamuro/projects/venv/lib/python3.9/site-packages/datumaro/components/dataset.py", line 700, in import_from
    else importer(path, **kwargs)
  File "/root/datamuro/projects/venv/lib/python3.9/site-packages/datumaro/components/importer.py", line 67, in __call__
    raise DatasetNotFoundError(path, self.NAME)
datumaro.components.errors.DatasetNotFoundError: Failed to find dataset 'roboflow_voc' at '/root/voc'
```

# Convert
## CLI
```
╰─❯ datum convert -if roboflow_voc -i /root/voc -f cvat -o ~/cvat-export
2023-10-01 14:56:35,121 ERROR: Failed to find dataset 'roboflow_voc' at '/root/voc'
Traceback (most recent call last):
  File "/root/datamuro/projects/venv/bin/datum", line 8, in <module>
    sys.exit(main())
  File "/root/datamuro/projects/venv/lib/python3.9/site-packages/datumaro/cli/__main__.py", line 150, in main
    retcode = args.command(args)
  File "/root/datamuro/projects/venv/lib/python3.9/site-packages/datumaro/cli/commands/convert.py", line 158, in convert_command
    dataset = Dataset.import_from(source, fmt, **import_kwargs)
  File "/root/datamuro/projects/venv/lib/python3.9/site-packages/datumaro/components/dataset.py", line 700, in import_from
    else importer(path, **kwargs)
  File "/root/datamuro/projects/venv/lib/python3.9/site-packages/datumaro/components/importer.py", line 67, in __call__
    raise DatasetNotFoundError(path, self.NAME)
datumaro.components.errors.DatasetNotFoundError: Failed to find dataset 'roboflow_voc' at '/root/voc'
```

I am trying to import and then export to CVAT so I can import my dataset into CVAT. Any advice would be greatly appreciated.

TIA!

**Comment by baudneo** [comment]
Hi, sorry to bug but I'm at a loss here. I desperately need to convert my exported roboflow dataset to something cvat can import.

My project is at a standstill until I can get this accomplished.

Please, can someone give me some advice? I've gone over the user manual and I'm stuck on the very first step in Basic Skills.

**Comment by sooahleex** [comment]
Hi @baudneo, Sorry for late response and thanks for your interest on our project.

In my understanding, you tried to import dataset with `roboflow-voc` format and convert it into `cvat` format.
The dataset I used for this test has same structure with you.
```
╰─❯ tree -d voc
voc
├── test
├── train
└── valid
```

I did those import and convert things in CLI like below.
```
cd ~/test
datum project create -o ./project1
datum project import -n cm-v7 --format roboflow_voc -p ./project1 ~/data/roboflow/voc/
datum convert -if roboflow_voc -i ~/data/roboflow/voc/ -f cvat -o ./cvat-export
```
And this works out for me with those kind of output `2023-10-04 18:36:35,404 INFO: Dataset exported to '/home/sooah/test/cvat-export' as 'cvat'`

If you met error like this `datumaro.components.errors.DatasetNotFoundError: Failed to find dataset 'roboflow_voc' at '/root/voc'`, then I recommend you to check whether the dataset structure is proper or not. You can check the supported structure of roboflow voc in [doc](https://openvinotoolkit.github.io/datumaro/latest/docs/data-formats/formats/roboflow.html#roboflow-voc-xml) and this is test [assets](https://github.com/openvinotoolkit/datumaro/tree/develop/tests/assets/roboflow_dataset/voc). You can compare your dataset structure with this. 

Please let me know if the your dataset structure is the same and the above CLI does not work for importing and converting. If you share the data with me, I will try it myself and tell you again.

**Comment by baudneo** [comment]
> Hi @baudneo, Sorry for late response and thanks for your interest on our project.
> 
> In my understanding, you tried to import dataset with `roboflow-voc` format and convert it into `cvat` format.
> The dataset I used for this test has same structure with you.
> ```
> ╰─❯ tree -d voc
> voc
> ├── test
> ├── train
> └── valid
> ```
> 
> I did those import and convert things in CLI like below.
> ```
> cd ~/test
> datum project create -o ./project1
> datum project import -n cm-v7 --format roboflow_voc -p ./project1 ~/data/roboflow/voc/
> datum convert -if roboflow_voc -i ~/data/roboflow/voc/ -f cvat -o ./cvat-export
> ```
> And this works out for me with those kind of output `2023-10-04 18:36:35,404 INFO: Dataset exported to '/home/sooah/test/cvat-export' as 'cvat'`
> 
> If you met error like this `datumaro.components.errors.DatasetNotFoundError: Failed to find dataset 'roboflow_voc' at '/root/voc'`, then I recommend you to check whether the dataset structure is proper or not. You can check the supported structure of roboflow voc in [doc](https://openvinotoolkit.github.io/datumaro/latest/docs/data-formats/formats/roboflow.html#roboflow-voc-xml) and this is test [assets](https://github.com/openvinotoolkit/datumaro/tree/develop/tests/assets/roboflow_dataset/voc). You can compare your dataset structure with this. 
> 
> Please let me know if the your dataset structure is the same and the above CLI does not work for importing and converting. If you share the data with me, I will try it myself and tell you again.

Hi, thanks for the reply. I will try this evening again. It's weird because I exported the dataset in VOC, coco, darknet and tfrecord. Cvat couldn't import those and the box and coco dataset wouldn't import to datamuro.

I'm going to try on another machine to see if maybe there's something up on the machine in question.

Thank you for your response and work!

**Comment by baudneo** [comment]
This is so weird...... I have been trying for a few days to convert my dataset. Ive exported into every format I can to try and convert and it just wont work. The farthest I have gotten is with COCO.

```
╰─❯ datum convert -if roboflow_coco -i /root/coco -f cvat -o ~/cvat-export
2023-10-06 21:11:01,241 ERROR: Failed to import dataset 'roboflow_coco' at '/root/coco'.
Traceback (most recent call last):
  File "/root/datamuro/projects/venv/lib/python3.9/site-packages/datumaro/components/dataset.py", line 736, in import_from
    env.make_extractor(src_conf.format, src_conf.url, **extractor_kwargs)
  File "/root/datamuro/projects/venv/lib/python3.9/site-packages/datumaro/components/environment.py", line 283, in make_extractor
    return self.extractors.get(name)(*args, **kwargs)
  File "/root/datamuro/projects/venv/lib/python3.9/site-packages/datumaro/plugins/data_formats/roboflow/base.py", line 50, in __init__
    super().__init__(
  File "/root/datamuro/projects/venv/lib/python3.9/site-packages/datumaro/plugins/data_formats/coco/base.py", line 143, in __init__
    self._load_categories(
  File "/root/datamuro/projects/venv/lib/python3.9/site-packages/datumaro/plugins/data_formats/coco/base.py", line 195, in _load_categories
    self._load_label_categories(
  File "/root/datamuro/projects/venv/lib/python3.9/site-packages/datumaro/plugins/data_formats/coco/base.py", line 246, in _load_label_categories
    categories.add(cat["name"], parent=cat.get("supercategory"))
  File "/root/datamuro/projects/venv/lib/python3.9/site-packages/datumaro/components/annotation.py", line 207, in add
    assert name not in self._indices, name
AssertionError: fish

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/root/datamuro/projects/venv/bin/datum", line 8, in <module>
    sys.exit(main())
  File "/root/datamuro/projects/venv/lib/python3.9/site-packages/datumaro/cli/__main__.py", line 150, in main
    retcode = args.command(args)
  File "/root/datamuro/projects/venv/lib/python3.9/site-packages/datumaro/cli/commands/convert.py", line 158, in convert_command
    dataset = Dataset.import_from(source, fmt, **import_kwargs)
  File "/root/datamuro/projects/venv/lib/python3.9/site-packages/datumaro/components/dataset.py", line 768, in import_from
    raise DatasetImportError(f"Failed to import dataset '{format}' at '{path}'.") from e
datumaro.components.errors.DatasetImportError: Failed to import dataset 'roboflow_coco' at '/root/coco'.
```

**Comment by baudneo** [comment]
The file structure for VOC/COCO is the same as in the docs. I cant see a reason as to why this is failing. I used `--loglevel debug` and it did not give me any useful debug information.

I am at a complete loss.

The workflow for this is:
1. Export dataset from roboflow in COCO format.
2. `mkdir /root/coco && mv ~/Downloads/dataset.zip /root/coco && cd /root/coco && unzip dataset.zip`
3. `╰─❯ datum --loglevel debug convert -if roboflow_coco -i /root/coco -f cvat -o ~/cvat-export` 

Here is the project URL in roboflow, you can export the dataset yourself and try to convert it: https://universe.roboflow.com/cm01-w9l8a/cm-ds-01


# Edit:
Come to think of it.... I do an augmentation that remaps classes, I wonder if somehow, roboflow has mangled something in the config?

**Comment by sooahleex** [comment]
Hi @baudneo I have reviewed the issue you reported. I downloaded the dataset from the link you provided in `COCO` format and attempted to import it into Datumaro. I encountered the same error during the dataset import process.

Upon investigation, I discovered that the issue lies within the annotation file. When I examined your dataset, I found that the categories were defined as follows in part of your annotation file (`train/_annotations.coco.json`):
```
"categories":[{"id":0,"name":"fish","supercategory":"none"},{"id":1,"name":"fish","supercategory":"fish"},{"id":2,"name":"lobster trap","supercategory":"fish"}]
```
This structure is consistent across `valid/_annotations.coco.json` and `test/_annotations.coco.json` as well. The error occurs because the `name` field of the categories is the same in the first and second categories.

To resolve this issue, I attempted to modify the name of the first category from **fish** to **default** as shown below:
```
"categories":[{"id":0,"name":"default","supercategory":"none"},{"id":1,"name":"fish","supercategory":"fish"},{"id":2,"name":"lobster trap","supercategory":"fish"}]
```

With this modification, the dataset could be successfully imported with the `roboflow_coco` format.

I recommend that you review the annotation file of your dataset. It appears that the `categories` in your dataset, which were imported from your project, may not be properly defined and do not include all the classes of the items. It seems that your data originally had classes such as "Acanthuridae -Surgeonfishes-," "Balistidae -Triggerfishes-," "Carangidae -Jacks-," ..., "lobster trap," ..., and "tuna," but the annotation file did not include all of them.

As a side note, when importing the Roboflow format into Datumaro, please ensure that:

1. The names of categories do not overlap.
2. Each item belongs to a single subset, not multiple subsets.

If you encounter the error again while using Datumaro, please don't hesitate to reach out for further assistance. Thank you for your interest in our project.
I hope this helps!

**Comment by baudneo** [comment]
You are my hero! Ive been tearing my hair out trying to get this figured.

Thank you very much for your help!

**Comment by baudneo** [comment]
Hi, It converts the annotation files but does not cp or mv the images. I also get several thousand lines of console output like this:

`2023-10-10 18:53:10,025 WARNING: Item FishDataset82_png_jpg.rf.0a27b783390786f1eaaa97625fad672a: skipping undeclared attribute 'is_crowd' for label 'fish' (allow with --allow-undeclared-attrs option)
2023-10-10 18:53:10,025 WARNING: Item FishDataset82_png_jpg.rf.0a27b783390786f1eaaa97625fad672a: skipping undeclared attribute 'is_crowd' for label 'fish' (allow with --allow-undeclared-attrs option)
2023-10-10 18:53:10,026 WARNING: Item FishDataset82_png_jpg.rf.0a27b783390786f1eaaa97625fad672a: skipping undeclared attribute 'is_crowd' for label 'fish' (allow with --allow-undeclared-attrs option)
2023-10-10 18:53:10,026 WARNING: Item FishDataset82_png_jpg.rf.0a27b783390786f1eaaa97625fad672a: skipping undeclared attribute 'is_crowd' for label 'fish' (allow with --allow-undeclared-attrs option)
2023-10-10 18:53:10,026 INFO: Dataset exported to '/root/cvat-export' as 'cvat'`

I tried adding `--allow-undeclared-attrs` but, I keep getting an error with that:

```
╰─❯ datum --loglevel debug --allow-undeclared-attrs convert -if roboflow_coco -i /root/coco -f cvat -o ~/cvat-export
usage: datum [-h] [--version] [--loglevel LOGLEVEL]
datum: error: unrecognized arguments: --allow-undeclared-attrs

╭─   ~/datamuro ─────────────────────────────────────────────────────────────── took  3s  datamuro with root@pve740 at  06:54:20 PM
╰─❯ datum --loglevel debug convert --allow-undeclared-attrs -if roboflow_coco -i /root/coco -f cvat -o ~/cvat-export
usage: datum [-h] [--version] [--loglevel LOGLEVEL]
datum: error: unrecognized arguments: --allow-undeclared-attrs
```

**Comment by sooahleex** [comment]
> Hi, It converts the annotation files but does not cp or mv the images. I also get several thousand lines of console output like this:
> 
> `2023-10-10 18:53:10,025 WARNING: Item FishDataset82_png_jpg.rf.0a27b783390786f1eaaa97625fad672a: skipping undeclared attribute 'is_crowd' for label 'fish' (allow with --allow-undeclared-attrs option) 2023-10-10 18:53:10,025 WARNING: Item FishDataset82_png_jpg.rf.0a27b783390786f1eaaa97625fad672a: skipping undeclared attribute 'is_crowd' for label 'fish' (allow with --allow-undeclared-attrs option) 2023-10-10 18:53:10,026 WARNING: Item FishDataset82_png_jpg.rf.0a27b783390786f1eaaa97625fad672a: skipping undeclared attribute 'is_crowd' for label 'fish' (allow with --allow-undeclared-attrs option) 2023-10-10 18:53:10,026 WARNING: Item FishDataset82_png_jpg.rf.0a27b783390786f1eaaa97625fad672a: skipping undeclared attribute 'is_crowd' for label 'fish' (allow with --allow-undeclared-attrs option) 2023-10-10 18:53:10,026 INFO: Dataset exported to '/root/cvat-export' as 'cvat'`
> 
> I tried adding `--allow-undeclared-attrs` but, I keep getting an error with that:
> 
> ```
> ╰─❯ datum --loglevel debug --allow-undeclared-attrs convert -if roboflow_coco -i /root/coco -f cvat -o ~/cvat-export
> usage: datum [-h] [--version] [--loglevel LOGLEVEL]
> datum: error: unrecognized arguments: --allow-undeclared-attrs
> 
> ╭─   ~/datamuro ─────────────────────────────────────────────────────────────── took  3s  datamuro with root@pve740 at  06:54:20 PM
> ╰─❯ datum --loglevel debug convert --allow-undeclared-attrs -if roboflow_coco -i /root/coco -f cvat -o ~/cvat-export
> usage: datum [-h] [--version] [--loglevel LOGLEVEL]
> datum: error: unrecognized arguments: --allow-undeclared-attrs
> ```

Hi @baudneo This is not an error message but rather an announcement that the 'is_crowd' attribute is not declared for the label 'fish' in your dataset, which is required for converting the CVAT format. The `--allow-undeclared-attrs` option is meant for the CVAT exporter.

If you would like to bypass this warning, you can follow these steps:
```
datum project create -o ./project1
datum project import -n cm-v7 --format roboflow_coco -p ./project1/ ~/data/CloudMule_v7i_coco_fix/
datum project export -o ./cvat-export -p ./project1/ -f cvat -- --allow-undeclared-attrs
```
This approach will work and provide you with the same result.
Thank you for your understanding and for using our project.

I hope this helps!
