### ISSUE TITLE
Export dataset from custom format

### ISSUE THREAD

**Issue by CourchesneA** [openvinotoolkit/datumaro#1209]
I am trying to create a datumaro dataset from a custom format that is not yet implemented.

I am using this function:
```
from datumaro.components.dataset import Dataset
from datumaro.components.dataset_base import DatasetItem
from datumaro.components.annotation import AnnotationType
from datumaro.components.media import Image

def convert_to_datumaro(dataset, output_dir):
    datumaro_dataset = Dataset(media_type=Image)
    for item_data in dataset:
        annotations = []
        for label, bbox in item_data['annotations']:
            annotations.append({
                'type': AnnotationType.bbox,
                'label': label,
                'points': bbox,
            })

        image_path = item_data['image']
        image_data = Image.from_file(image_path)

        datumaro_dataset.put(DatasetItem(
            id=image_path,
            media=image_data,
            annotations=annotations,
            attributes=item_data['metadata']
        ))
```

however when I try to export or save this dataset, I get the following error:

```
Traceback (most recent call last):
  File "/home/myself/venv/lib/python3.10/site-packages/datumaro/components/dataset.py", line 651, in save
    self.export(save_dir or self._source_path, format=self._format, **options)
  File "/home/myself/venv/lib/python3.10/site-packages/datumaro/util/scope.py", line 158, in wrapped_func
    ret_val = func(*args, **kwargs)
  File "/home/myself/venv/lib/python3.10/site-packages/datumaro/components/dataset.py", line 606, in export
    exporter.convert(self, save_dir=save_dir, **exporter_kwargs)
  File "/home/myself/venv/lib/python3.10/site-packages/datumaro/components/exporter.py", line 124, in convert
    return converter.apply()
  File "/home/myself/venv/lib/python3.10/site-packages/datumaro/components/exporter.py", line 159, in apply
    return self._apply_impl()
  File "/home/myself/venv/lib/python3.10/site-packages/datumaro/plugins/data_formats/datumaro/exporter.py", line 506, in _apply_impl
    writers[subset_name].add_item(item, pool)
  File "/home/myself/venv/lib/python3.10/site-packages/datumaro/plugins/data_formats/datumaro/exporter.py", line 146, in add_item
    self.items.append(self._gen_item_desc(item))
  File "/home/myself/venv/lib/python3.10/site-packages/datumaro/plugins/data_formats/datumaro/exporter.py", line 210, in _gen_item_desc
    raise NotImplementedError()
```

I assume that is because my custom format is not supported and there is no exporter for it. Can I get around that without having to write all the code to get an exporter ?

**Comment by vinnamkim** [comment]
Hi @CourchesneA,
Thanks for your interest on our project.

First of all, I'd like to ask you that I'm understanding your question correctly.

1. You want to construct your own dataset as `Datumaro.Dataset` object.
2. Using `Datumaro.Dataset.export(format="what_you_want")` function to export your dataset to an arbitrary data format.

As shown in [this example from our docs](https://openvinotoolkit.github.io/datumaro/latest/docs/get-started/quick-start-guide/examples.html), you have to create the annotation object `Bbox` for `DatasetItem.annotations` field as well. The error message you received itself comes because you gave the Python dictionary objects to that field.

```python
import numpy as np
import datumaro as dm

dataset = dm.Dataset.from_iterable([
  dm.DatasetItem(id='image1', subset='train',
    media=dm.Image.from_numpy(data=np.ones((5, 5, 3))),
    annotations=[
      dm.Bbox(1, 2, 3, 4, label=0),
    ]
  ),
  # ...
], categories=['cat', 'dog'])
dataset.export('test_dataset/', 'coco')
```

Therefore, I'm thinking that I can fix your code as follows.
```python
from datumaro.components.dataset import Dataset
from datumaro.components.dataset_base import DatasetItem
from datumaro.components.annotation import Bbox
from datumaro.components.media import Image


def create_item(item_data):
    annotations = []
    [
        Bbox(x=bbox.x, y=bbox.y, w=bbox.w, h=bbox.h, label=label)
        # label should be integer if categories=["label_1", "label_2", ...],
        # then label=0 points to "label_1" and label=1 points to "label_2".
        for label, bbox in item_data["annotations"]
    ]
    image_path = item_data["image"]
    image_data = Image.from_file(image_path)

    return DatasetItem(
        id=image_path,
        media=image_data,
        annotations=annotations,
        attributes=item_data["metadata"],  # item_data['metadata'] should be Python dictionary
    )


def convert_to_datumaro(dataset, output_dir):
    dataset = Dataset.from_iterable(
        iterable=[create_item(item_data) for item_data in dataset],
        categories=["label_1", "label_2", ...],
        media_type=Image,
    )
    # If you want that the exported dataset has media files (Image), set save_media=True
    dataset.export(save_dir=output_dir, format="format_what_you_want", save_media=True)
```

**Comment by CourchesneA** [comment]
That is what I was missing. Thanks a lot !
