### ISSUE TITLE
AttributeError when running CLI with version 1.6.0

### ISSUE THREAD

**Issue by jarkenau** [openvinotoolkit/datumaro#1444]
When I install Datumaro via  with `pip install datumaro[default]` version `1.6.0` is used. I get the following error when using the CLI, for example `datum --help` produces:

```shell 
Traceback (most recent call last):
  File "/home/docker/.local/bin/datum", line 5, in <module>
    from datumaro.cli.__main__ import main
  File "/home/docker/.local/lib/python3.10/site-packages/datumaro/cli/__main__.py", line 11, in <module>
    from ..util.telemetry_utils import (
  File "/home/docker/.local/lib/python3.10/site-packages/datumaro/util/telemetry_utils.py", line 12, in <module>
    from datumaro.cli import commands, contexts
  File "/home/docker/.local/lib/python3.10/site-packages/datumaro/cli/commands/__init__.py", line 7, in <module>
    from . import (
  File "/home/docker/.local/lib/python3.10/site-packages/datumaro/cli/commands/download.py", line 14, in <module>
    from datumaro.components.extractor_tfds import (
  File "/home/docker/.local/lib/python3.10/site-packages/datumaro/components/extractor_tfds.py", line 49, in <module>
    tfds = lazy_import("tensorflow_datasets")
  File "/home/docker/.local/lib/python3.10/site-packages/datumaro/util/import_util.py", line 13, in lazy_import
    loader = importlib.util.LazyLoader(spec.loader)
AttributeError: 'NoneType' object has no attribute 'loader'
```

The error does not occur in version `1.5.2` 

Other specs:

Python Version: `3.10.12`
Pip Version: `24.0`
OS: `Ubuntu 22.04`

**Comment by jihyeonyi** [comment]
Hi @jarkenau, 
Thank you for the reporting this bug. 
I've prepared the fix (#1454).

**Comment by wonjuleee** [comment]
Thanks @jihyeonyi, I will close this issue.

**Comment by Abdul-Mukit** [comment]
@wonjuleee I am still getting this error.  

```
  File "/home/projects/dataset/.venv/lib/python3.13/site-packages/datumaro/cli/util/compare.py", line 28, in <module>
    tb = lazy_import("tensorboardX")
  File "/home/projects/dataset/.venv/lib/python3.13/site-packages/datumaro/util/import_util.py", line 13, in lazy_import
    loader = importlib.util.LazyLoader(spec.loader)
                                       ^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'loader'

```

Setup:
```
datumaro 1.12.0
Python 3.13.5
debian 13
```

**Comment by Abdul-Mukit** [comment]
Solved by `pip install tensorboardX`
