### ISSUE TITLE
can't transform imagenet data

### ISSUE THREAD

**Issue by jihyeonyi** [openvinotoolkit/datumaro#163]

**Comment by jihyeonyi** [comment]
When loading imagenet format data, I can't transform it. 
I've checked only classification-split and ndr only, but I think it would be similar to other transforms.
Here is my error log.
```bash
$ datum project transform -t classification_split -p imagenet_val2/ -- --subset train:.5 --subset val:.2 --subset test:.3
2021-03-16 17:33:58,118 WARNING: Failed to import module 'accuracy_checker_plugin.launcher.py': numpy.ndarray size changed, may indicate binary incompatibility. Expected 88 from C header, got 80 from PyObject
2021-03-16 17:33:58,119 WARNING: Failed to import module 'datumaro_format.converter.py': numpy.ndarray size changed, may indicate binary incompatibility. Expected 88 from C header, got 80 from PyObject
2021-03-16 17:33:58,121 WARNING: Failed to import module 'coco_format.converter.py': numpy.ndarray size changed, may indicate binary incompatibility. Expected 88 from C header, got 80 from PyObject
2021-03-16 17:33:58,139 WARNING: Failed to import module 'coco_format.extractor.py': numpy.ndarray size changed, may indicate binary incompatibility. Expected 88 from C header, got 80 from PyObject
2021-03-16 17:33:58,180 WARNING: Failed to import module 'openvino_launcher.py': libpython3.7m.so.1.0: cannot open shared object file: No such file or directory
2021-03-16 17:33:58,181 WARNING: Failed to import module 'transforms.py': numpy.ndarray size changed, may indicate binary incompatibility. Expected 88 from C header, got 80 from PyObject
2021-03-16 17:33:58,218 INFO: Loading the project...
2021-03-16 17:34:00,147 INFO: Transforming the project...
2021-03-16 17:34:01,205 ERROR: 'datumaro'
Traceback (most recent call last):
  File "/home/jihyeony/workspace/miniconda3/envs/datumaro/bin/datum", line 33, in <module>
    sys.exit(load_entry_point('datumaro', 'console_scripts', 'datum')())
  File "/mnt/hdd2/workspace/datumaro/datumaro/datumaro/cli/__main__.py", line 122, in main
    return args.command(args)
  File "/mnt/hdd2/workspace/datumaro/datumaro/datumaro/cli/contexts/project/__init__.py", line 683, in transform_command
    dataset.transform_project(
  File "/mnt/hdd2/workspace/datumaro/datumaro/datumaro/components/project.py", line 295, in transform_project
    self._save_branch_project(transformed, save_dir=save_dir)
  File "/mnt/hdd2/workspace/datumaro/datumaro/datumaro/components/project.py", line 252, in _save_branch_project
    dst_dataset.save(save_dir=save_dir, merge=True)
  File "/mnt/hdd2/workspace/datumaro/datumaro/datumaro/components/project.py", line 197, in save
    self.env.converters.get(DEFAULT_FORMAT).convert(
  File "/mnt/hdd2/workspace/datumaro/datumaro/datumaro/components/environment.py", line 41, in get
    return self.items[key]
KeyError: 'datumaro'
```

**Comment by jihyeonyi** [comment]
Wait, please.
I seems that there was an error while installing datumaro.
I'll check again.

**Comment by jihyeonyi** [comment]
Oh, this was my fault.
There were conflicts while installation, and there's no error after fixing them.
Sorry for the bother.
I'll close this issue.
