### ISSUE TITLE
Import CamVid dataset

### ISSUE THREAD

**Issue by kirill-sizov** [openvinotoolkit/datumaro#338]
### Steps to reproduce
1. [Load the original CamVid dataset](https://www.kaggle.com/carlolepelaars/camvid);
2. Import the loaded dataset into a Datumaro project.

### Current behaviour
Import with error:
```bash
Traceback (most recent call last):
  File "/home/ksizov/d2/datumaro/venv/bin/datum", line 33, in <module>
    sys.exit(load_entry_point('datumaro', 'console_scripts', 'datum')())
  File "/home/ksizov/d2/datumaro/datumaro/cli/__main__.py", line 126, in main
    return args.command(args)
  File "/home/ksizov/d2/datumaro/datumaro/cli/contexts/source.py", line 169, in add_command
    project.make_source_project(name).make_dataset()
  File "/home/ksizov/d2/datumaro/datumaro/components/project.py", line 425, in make_dataset
    return ProjectDataset(self)
  File "/home/ksizov/d2/datumaro/datumaro/components/project.py", line 63, in __init__
    sources[s_name] = Dataset.import_from(url,
  File "/home/ksizov/d2/datumaro/datumaro/components/dataset.py", line 815, in import_from
    extractors.append(env.make_extractor(
  File "/home/ksizov/d2/datumaro/datumaro/components/environment.py", line 274, in make_extractor
    return self.extractors.get(name)(*args, **kwargs)
  File "/home/ksizov/d2/datumaro/datumaro/plugins/camvid_format.py", line 148, in __init__
    self._items = list(self._load_items(path).values())
  File "/home/ksizov/d2/datumaro/datumaro/plugins/camvid_format.py", line 190, in _load_items
    mask = mask() # loading mask through cache
  File "/home/ksizov/d2/datumaro/datumaro/util/image.py", line 223, in __call__
    image = self.loader(self.path)
  File "/home/ksizov/d2/datumaro/datumaro/util/mask_tools.py", line 132, in <lambda>
    return lazy_image(path, lambda path: load_mask(path, inverse_colormap))
  File "/home/ksizov/d2/datumaro/datumaro/util/mask_tools.py", line 128, in load_mask
    mask = unpaint_mask(mask, inverse_colormap)
  File "/home/ksizov/d2/datumaro/datumaro/util/mask_tools.py", line 70, in unpaint_mask
    palette = np.array([map_fn(v) for v in uvals],
  File "/home/ksizov/d2/datumaro/datumaro/util/mask_tools.py", line 70, in <listcomp>
    palette = np.array([map_fn(v) for v in uvals],
  File "/home/ksizov/d2/datumaro/datumaro/util/mask_tools.py", line 61, in <lambda>
    map_fn = lambda a: inverse_colormap[(
KeyError: (2, 2, 0)
```

### Expected behaviour
Successful importing.

**Comment by kirill-sizov** [comment]
This problem occurs because the original CamVid dataset contains unmarked color masks and Datumaro does not handle this situation because there is no solution to unambiguously interpret this.

And to load the original dataset without errors user can remove the test subset from the directory with dataset because the test subset in the CamVid dataset contains invalid masks.
