### ISSUE TITLE
Merging Projects

### ISSUE THREAD

**Issue by brunovollmer** [openvinotoolkit/datumaro#413]
Hello,

what would be the workflow if I wanted to merge multiple datasets which have **no** overlapping images/annotations? 
`datum merge project1 project2` is super slow and I think there are some checks in the background which I don't need. 
Additionally once there are merged is there an option to merge all subsets into one?

Thanks

**Comment by zhiltsov-max** [comment]
Hi, please check this answer https://github.com/openvinotoolkit/datumaro/issues/256#issuecomment-858052945

**Comment by brunovollmer** [comment]
Thanks for the answer. I will have a look. A question regarding the regular merge commmand. I ran `datum merge project1 project2` successfully where project one is the coco dataset and project two is the voc2012 dataset export with the coco_instances format option. Now when I try to use `datum info` I receive the following error:
```
2021-08-19 14:14:39,306 WARNING: Failed to import module 'coco_format.extractor.py': numpy.ndarray size changed, may indicate binary incompatibility. Expected 88 from C header, got 80 from PyObject
2021-08-19 14:14:39,309 WARNING: Failed to import module 'coco_format.converter.py': numpy.ndarray size changed, may indicate binary incompatibility. Expected 88 from C header, got 80 from PyObject
2021-08-19 14:14:40,785 WARNING: Failed to import module 'datumaro_format.converter.py': numpy.ndarray size changed, may indicate binary incompatibility. Expected 88 from C header, got 80 from PyObject
2021-08-19 14:14:40,788 WARNING: Failed to import module 'transforms.py': numpy.ndarray size changed, may indicate binary incompatibility. Expected 88 from C header, got 80 from PyObject
2021-08-19 14:14:41,292 ERROR: 'coco_instances'
Traceback (most recent call last):
  File "/anaconda/envs/azureml_py38/bin/datum", line 8, in <module>
    sys.exit(main())
  File "/anaconda/envs/azureml_py38/lib/python3.8/site-packages/datumaro/cli/__main__.py", line 125, in main
    return args.command(args)
  File "/anaconda/envs/azureml_py38/lib/python3.8/site-packages/datumaro/cli/contexts/project/__init__.py", line 744, in info_command
    dataset = project.make_dataset()
  File "/anaconda/envs/azureml_py38/lib/python3.8/site-packages/datumaro/components/project.py", line 427, in make_dataset
    return ProjectDataset(self)
  File "/anaconda/envs/azureml_py38/lib/python3.8/site-packages/datumaro/components/project.py", line 65, in __init__
    sources[s_name] = Dataset.import_from(url,
  File "/anaconda/envs/azureml_py38/lib/python3.8/site-packages/datumaro/components/dataset.py", line 819, in import_from
    extractors.append(env.make_extractor(
  File "/anaconda/envs/azureml_py38/lib/python3.8/site-packages/datumaro/components/environment.py", line 278, in make_extractor
    return self.extractors.get(name)(*args, **kwargs)
  File "/anaconda/envs/azureml_py38/lib/python3.8/site-packages/datumaro/components/environment.py", line 33, in get
    return self.items[key]
KeyError: 'coco_instances'

```

**Comment by brunovollmer** [comment]
And regarding your answer is there an option to adjust the labels to each other?

**Comment by zhiltsov-max** [comment]
Looking at the warnings, I think, you can have problems with the `numpy` dependency. It looks similar to #116, so try to remove `pycocotools`, then reinstall it with `pip install pycocotools --no-binary`.

> And regarding your answer is there an option to adjust the labels to each other?

It can be done with the heavy merge command, with the `remap_labels` transform, or with the code snippet from my answer above.

**Comment by brunovollmer** [comment]
sorry that I'm asking that much. When I remapped the labels it exports something into a sub-folder. Why can't I create a datumaro project from it or how am I supposed to use it? The original dataset stayed the same.

**Comment by zhiltsov-max** [comment]
If you used `datum transform`, the resulting directory is a Datumaro project, which can be used directly.

**Comment by zhiltsov-max** [comment]
Since v0.2, the recommended way to merge datasets in simple cases is using the [patch command](https://openvinotoolkit.github.io/datumaro/docs/user-manual/command-reference/patch/).
