### ISSUE TITLE
Failed to install Datumaro

### ISSUE THREAD

**Issue by zhiltsov-max** [openvinotoolkit/datumaro#646]
<details>

```
$ pip install datumaro
Collecting datumaro
  Using cached datumaro-0.2.3-py3-none-any.whl (340 kB)
Requirement already satisfied: defusedxml>=0.7.0 in /lib/python3.8/site-packages (from datumaro) (0.7.1)
Collecting tensorboardX!=2.3,>=1.8
  Downloading tensorboardX-2.4.1-py2.py3-none-any.whl (124 kB)
     |████████████████████████████████| 124 kB 432 kB/s 
Requirement already satisfied: scipy in /lib/python3.8/site-packages (from datumaro) (1.6.3)
Requirement already satisfied: opencv-python in /lib/python3.8/site-packages (from datumaro) (4.5.3.56)
Collecting lxml>=4.4.1
  Downloading lxml-4.7.1-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.manylinux_2_24_x86_64.whl (6.9 MB)
     |████████████████████████████████| 6.9 MB 2.2 MB/s 
Requirement already satisfied: networkx>=2.5 in /lib/python3.8/site-packages (from datumaro) (2.5.1)
Requirement already satisfied: PyYAML>=5.3.1 in /lib/python3.8/site-packages (from datumaro) (5.3.1)
Requirement already satisfied: matplotlib>=3.3.1 in /lib/python3.8/site-packages (from datumaro) (3.4.3)
Requirement already satisfied: typing-extensions>=3.7.4.3 in /lib/python3.8/site-packages (from datumaro) (3.7.4.3)
Requirement already satisfied: Pillow>=6.1.0 in /lib/python3.8/site-packages (from datumaro) (8.3.1)
Requirement already satisfied: pandas>=1.1.5 in /lib/python3.8/site-packages (from datumaro) (1.2.4)
Requirement already satisfied: ruamel.yaml>=0.17.0 in /lib/python3.8/site-packages (from datumaro) (0.17.16)
Requirement already satisfied: attrs>=21.1.0 in /lib/python3.8/site-packages (from datumaro) (21.2.0)
Collecting pycocotools>=2.0.4; platform_system != "Windows" or python_version >= "3.9"
  Using cached pycocotools-2.0.4.tar.gz (106 kB)
  Installing build dependencies ... error
  ERROR: Command errored out with exit status 1:
   command: /bin/python /lib/python3.8/site-packages/pip install --ignore-installed --no-user --prefix /tmp/pip-build-env-n0bc93uv/overlay --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- 'cython>=0.27.3' oldest-supported-numpy 'setuptools>=43.0.0' wheel
       cwd: None
  Complete output (42 lines):
  Traceback (most recent call last):
    File "/lib/python3.8/runpy.py", line 194, in _run_module_as_main
      return _run_code(code, main_globals, None,
    File "/lib/python3.8/runpy.py", line 87, in _run_code
      exec(code, run_globals)
    File "/lib/python3.8/site-packages/pip/__main__.py", line 26, in <module>
      sys.exit(_main())
    File "/lib/python3.8/site-packages/pip/_internal/cli/main.py", line 73, in main
      command = create_command(cmd_name, isolated=("--isolated" in cmd_args))
    File "/lib/python3.8/site-packages/pip/_internal/commands/__init__.py", line 104, in create_command
      module = importlib.import_module(module_path)
    File "/lib/python3.8/importlib/__init__.py", line 127, in import_module
      return _bootstrap._gcd_import(name[level:], package, level)
    File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
    File "<frozen importlib._bootstrap>", line 991, in _find_and_load
    File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
    File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
    File "<frozen importlib._bootstrap_external>", line 843, in exec_module
    File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
    File "/lib/python3.8/site-packages/pip/_internal/commands/install.py", line 17, in <module>
      from pip._internal.cli.req_command import RequirementCommand, with_cleanup
    File "/lib/python3.8/site-packages/pip/_internal/cli/req_command.py", line 16, in <module>
      from pip._internal.index.collector import LinkCollector
    File "/lib/python3.8/site-packages/pip/_internal/index/collector.py", line 14, in <module>
      from pip._vendor import html5lib, requests
    File "/lib/python3.8/site-packages/pip/_vendor/requests/__init__.py", line 125, in <module>
      from . import utils
    File "/lib/python3.8/site-packages/pip/_vendor/requests/utils.py", line 25, in <module>
      from . import certs
    File "/lib/python3.8/site-packages/pip/_vendor/requests/certs.py", line 15, in <module>
      from pip._vendor.certifi import where
    File "/lib/python3.8/site-packages/pip/_vendor/certifi/__init__.py", line 1, in <module>
      from .core import contents, where
    File "/lib/python3.8/site-packages/pip/_vendor/certifi/core.py", line 12, in <module>
      from importlib.resources import path as get_path, read_text
    File "/lib/python3.8/importlib/resources.py", line 11, in <module>
      from typing import Iterable, Iterator, Optional, Set, Union   # noqa: F401
    File "/lib/python3.8/site-packages/typing.py", line 1359, in <module>
      class Callable(extra=collections_abc.Callable, metaclass=CallableMeta):
    File "/lib/python3.8/site-packages/typing.py", line 1007, in __new__
      self._abc_registry = extra._abc_registry
  AttributeError: type object 'Callable' has no attribute '_abc_registry'
  ----------------------------------------
ERROR: Command errored out with exit status 1: /bin/python /lib/python3.8/site-packages/pip install --ignore-installed --no-user --prefix /tmp/pip-build-env-n0bc93uv/overlay --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- 'cython>=0.27.3' oldest-supported-numpy 'setuptools>=43.0.0' wheel Check the logs for full command output.
```

</details>

**Comment by zhiltsov-max** [comment]
Fixed by uninstalling typing
